site_name: BISICLES user documents

markdown_extensions:
  - toc:
      toc_depth: 1-2


theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - bash
    - python
    - c++
    - c

nav:
  - Home: index.md
  - Building and running: 
    - Generic instructions: readme.md
    - Site notes: sites.md
    - Common issues: trouble.md
  - Executables:
    - Main program (driver): driver.md
    - File tools: filetools.md
    - C/Fortran API: cdriver.md
  - Run time options:
    - Input and output: io.md
    - Ice sheet geometry: geometry.md
    - Stresses : stress.md
    - Thermodynamics: thermodynamics.md
    - Ice velocity: velocity.md
    - Surface fluxes: surfaceflux.md
    - LevelData interface: leveldatainterface.md
    - Python interface: pythoninterface.md
  - Examples:
    - MISMIP3D: readme.md#running-bisicles-on-a-simple-problem
    - Pine Island Glacier: pineisland.md
    - PIG inverse problem: pineislandinverse.md
  - Data viz / analysis: 
    - Python/R/MATLAB (libamrfile): libamrfile.md
    - VisIt: visit.md
  
