name: system regression test

on:

    workflow_dispatch:
#        branches: [ "master" ]
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
   
    #Install hdf5 etc
    - name: install dependencies
      run: | 
          sudo apt install gfortran csh mpi-default-bin mpi-default-dev 
          sudo apt install libhdf5-mpi-dev libhdf5-dev hdf5-tools 
          sudo apt install libnetcdff-dev libnetcdf-dev netcdf-bin nco
          sudo apt install python3 python3-dev libpython3-dev
          sudo apt install libfftw3-dev  

    #Retrieve cached chombo, or build
    - name: cache chombo
      id: cache-chombo
      uses: actions/cache@v4
      env:
          cache-name: cache-chombo
      with:
          path: Chombo
          key: ${{ runner.os }}-build-${{ env.cache-name }}
    
    - if: ${{ steps.cache-chombo.outputs.cache-hit != 'true' }}
      name: clone and build chombo
      run: |
            git clone https://github.com/applied-numerical-algorithms-group-lbnl/Chombo_3.2.git Chombo
            ls Chombo
            cp .github/workflows/Make.defs.local.ubuntu-22.04 Chombo/lib/mk/Make.defs.local
            cd Chombo/lib
            cat mk/Make.defs.local
            make lib OPT=TRUE MPI=TRUE -j4
         
    - name: list 
      run: | 
        echo $PWD
        ls -lh

            #    - name: build bisicles
            # run: |
            #cd $GITHUB_WORKSPACE/code/mk
            #ln -s Make.defs.ubuntu_22.4 Make.defs.`uname -n`
            #echo "CHOMBO_HOME=$GITHUB_WORKSPACE/Chombo" >> Make.defs.`uname -n`
            #cat Make.defs.`uname -n`
            #cd $GITHUB_WORKSPACE/code/exec2D
            #make all OPT=TRUE MPI=TRUE -j4

