name: system regression test

on:

    workflow_dispatch:
        branches: [ "master" ]
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    
    - name: cache chombo
      id: cache-chombo
      uses: actions/cache@v4
      env:
          cache-name: cache-chombo
      with:
          path: $GITHUB_WORKSPACE/Chombo
          key: ${{ runner.os }}-build-${{ env.cache-name }}
    
    - if: ${{ steps.cache-chombo.outputs.cache-hit != 'true' }}
      name: clone and build chombo
      run: |
            git clone https://github.com/applied-numerical-algorithms-group-lbnl/Chombo_3.2.git ../Chombo
            ls ../Chombo
            cp .github/workflows/Make.defs.local.ubuntu-22.04 ../Chombo/lib/mk/Make.defs.local
            cd ../Chombo/lib
            cat mk/Make.defs.local
            make all OPT=TRUE -j4
          
