name: system regression test

on:

    workflow_dispatch:
        branches: [ "master" ]
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: clone Chombo
      run: |
          git clone https://github.com/applied-numerical-algorithms-group-lbnl/Chombo_3.2.git ../Chombo
          ls ../Chombo
          
