name: report system information

on:

    workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04, ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
   
    #report CPU info
    - name: CPU info
      run: cat /proc/cpuinfo 
